// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwfmijuyjzwjyspqaqsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3Zm1panV5anp3anlzcHFhcXNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTU3MTYsImV4cCI6MjA2MDk3MTcxNn0.rvTQ40LTJVC-p0JmIG7ERuTsxqpoYSvVQA6u32F-sBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);